// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportPro.Web.Data;

#nullable disable

namespace SportPro.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240813103901_Add_Prihodi")]
    partial class Add_Prihodi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtikliBoje", b =>
                {
                    b.Property<int>("ArtikliIDArtikal")
                        .HasColumnType("int");

                    b.Property<int>("BojeIDBoja")
                        .HasColumnType("int");

                    b.HasKey("ArtikliIDArtikal", "BojeIDBoja");

                    b.HasIndex("BojeIDBoja");

                    b.ToTable("ArtikliBoje");
                });

            modelBuilder.Entity("ArtikliKategorije", b =>
                {
                    b.Property<int>("ArtikliIDArtikal")
                        .HasColumnType("int");

                    b.Property<int>("KategorijeIDKategorija")
                        .HasColumnType("int");

                    b.HasKey("ArtikliIDArtikal", "KategorijeIDKategorija");

                    b.HasIndex("KategorijeIDKategorija");

                    b.ToTable("ArtikliKategorije");
                });

            modelBuilder.Entity("ArtikliPoslovnice", b =>
                {
                    b.Property<int>("ArtikliIDArtikal")
                        .HasColumnType("int");

                    b.Property<int>("PoslovniceIDPoslovnica")
                        .HasColumnType("int");

                    b.HasKey("ArtikliIDArtikal", "PoslovniceIDPoslovnica");

                    b.HasIndex("PoslovniceIDPoslovnica");

                    b.ToTable("ArtikliPoslovnice");
                });

            modelBuilder.Entity("ArtikliVelicine", b =>
                {
                    b.Property<int>("ArtikliIDArtikal")
                        .HasColumnType("int");

                    b.Property<int>("VelicineIDVelicina")
                        .HasColumnType("int");

                    b.HasKey("ArtikliIDArtikal", "VelicineIDVelicina");

                    b.HasIndex("VelicineIDVelicina");

                    b.ToTable("ArtikliVelicine");
                });

            modelBuilder.Entity("KandidatiNatjecaji", b =>
                {
                    b.Property<int>("KandidatiIDKandidat")
                        .HasColumnType("int");

                    b.Property<int>("NatjecajiIDNatjecaj")
                        .HasColumnType("int");

                    b.HasKey("KandidatiIDKandidat", "NatjecajiIDNatjecaj");

                    b.HasIndex("NatjecajiIDNatjecaj");

                    b.ToTable("KandidatiNatjecaji");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01abf0a5-ef31-48b1-82db-7e274a7dbd71",
                            ConcurrencyStamp = "01abf0a5-ef31-48b1-82db-7e274a7dbd71",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "ca051bf6-5592-4a4d-a9c5-5f7c1530e61d",
                            ConcurrencyStamp = "ca051bf6-5592-4a4d-a9c5-5f7c1530e61d",
                            Name = "Uposlenik",
                            NormalizedName = "Uposlenik"
                        },
                        new
                        {
                            Id = "bf5c73e6-1743-4c02-a224-f7d5908eaa40",
                            ConcurrencyStamp = "bf5c73e6-1743-4c02-a224-f7d5908eaa40",
                            Name = "Vlasnik",
                            NormalizedName = "Vlasnik"
                        },
                        new
                        {
                            Id = "6b8f5bad-e5ca-43e9-ac46-ca02e0c96c5f",
                            ConcurrencyStamp = "6b8f5bad-e5ca-43e9-ac46-ca02e0c96c5f",
                            Name = "Menadzer",
                            NormalizedName = "Menadzer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "098294f1-5451-4a33-a567-5922f7c39c4e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2600fe3-9db7-4e00-af94-efc2b8cf896d",
                            Email = "vlasnik@sportpro.ba",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLASNIK@SPORTPRO.BA",
                            NormalizedUserName = "VLASNIK",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3QwCjXUeIALQUfkgi4QRK3zWiCJIPljeD6lEPcUnnCBqMNyQREmgpmUk5n5JNh6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1ba9b01-2a4d-4d95-bd44-8635ef909dc4",
                            TwoFactorEnabled = false,
                            UserName = "vlasnik"
                        },
                        new
                        {
                            Id = "2818ecc2-5e74-4df0-a503-57ea46cc3f7c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7251724-897a-4f43-927e-d125ce4c0dec",
                            Email = "admin@sportpro.ba",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SPORTPRO.BA",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGU8oqzik1LrFse7UK4XG4WY4J9xwBfro0mRjL5SArgKElFAVmoXY9CAxyawkCxY9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c30212dd-6e44-4599-8953-28384768d341",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "098294f1-5451-4a33-a567-5922f7c39c4e",
                            RoleId = "01abf0a5-ef31-48b1-82db-7e274a7dbd71"
                        },
                        new
                        {
                            UserId = "098294f1-5451-4a33-a567-5922f7c39c4e",
                            RoleId = "ca051bf6-5592-4a4d-a9c5-5f7c1530e61d"
                        },
                        new
                        {
                            UserId = "098294f1-5451-4a33-a567-5922f7c39c4e",
                            RoleId = "bf5c73e6-1743-4c02-a224-f7d5908eaa40"
                        },
                        new
                        {
                            UserId = "098294f1-5451-4a33-a567-5922f7c39c4e",
                            RoleId = "6b8f5bad-e5ca-43e9-ac46-ca02e0c96c5f"
                        },
                        new
                        {
                            UserId = "2818ecc2-5e74-4df0-a503-57ea46cc3f7c",
                            RoleId = "01abf0a5-ef31-48b1-82db-7e274a7dbd71"
                        },
                        new
                        {
                            UserId = "2818ecc2-5e74-4df0-a503-57ea46cc3f7c",
                            RoleId = "ca051bf6-5592-4a4d-a9c5-5f7c1530e61d"
                        },
                        new
                        {
                            UserId = "2818ecc2-5e74-4df0-a503-57ea46cc3f7c",
                            RoleId = "6b8f5bad-e5ca-43e9-ac46-ca02e0c96c5f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PozicijeZaposlenici", b =>
                {
                    b.Property<int>("PozicijeIDPozicija")
                        .HasColumnType("int");

                    b.Property<int>("ZaposleniciIDZaposlenik")
                        .HasColumnType("int");

                    b.HasKey("PozicijeIDPozicija", "ZaposleniciIDZaposlenik");

                    b.HasIndex("ZaposleniciIDZaposlenik");

                    b.ToTable("PozicijeZaposlenici");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Artikli", b =>
                {
                    b.Property<int>("IDArtikal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDArtikal"));

                    b.Property<int>("BrendIDBrend")
                        .HasColumnType("int");

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<double>("CijenaDostave")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumNabave")
                        .HasColumnType("datetime2");

                    b.Property<int>("DobavljacIDDobavljac")
                        .HasColumnType("int");

                    b.Property<bool>("NaStanju")
                        .HasColumnType("bit");

                    b.Property<double>("NabavnaCijena")
                        .HasColumnType("float");

                    b.Property<int>("NabavnaKolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Snizen")
                        .HasColumnType("bit");

                    b.Property<double>("SnizenaCijena")
                        .HasColumnType("float");

                    b.Property<int>("TrenutnaKolicina")
                        .HasColumnType("int");

                    b.Property<double?>("UkupnaZarada")
                        .HasColumnType("float");

                    b.Property<double>("UkupniTrosak")
                        .HasColumnType("float");

                    b.HasKey("IDArtikal");

                    b.HasIndex("BrendIDBrend");

                    b.HasIndex("DobavljacIDDobavljac");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Boje", b =>
                {
                    b.Property<int>("IDBoja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBoja"));

                    b.Property<string>("NazivBoje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDBoja");

                    b.ToTable("Boje");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Brendovi", b =>
                {
                    b.Property<int>("IDBrend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBrend"));

                    b.Property<int>("GodinaOsnivanja")
                        .HasColumnType("int");

                    b.Property<string>("NazivBrenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Osnivac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predsjednik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sjediste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDBrend");

                    b.ToTable("Brendovi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Certifikati", b =>
                {
                    b.Property<int>("IDCertifikat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCertifikat"));

                    b.Property<DateTime>("DatumDodjele")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCertifikat");

                    b.ToTable("Certifikati");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Dashboard", b =>
                {
                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Dobavljaci", b =>
                {
                    b.Property<int>("IDDobavljac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDobavljac"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KrajSuradnje")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PocetakSuradnje")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuradnjaAktivna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDobavljac");

                    b.ToTable("Dobavljaci");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Kandidati", b =>
                {
                    b.Property<int>("IDKandidat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKandidat"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKandidat");

                    b.ToTable("Kandidati");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Kategorije", b =>
                {
                    b.Property<int>("IDKategorija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKategorija"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKategorija");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.KategorijePrihoda", b =>
                {
                    b.Property<int>("IDKategorijePrihoda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKategorijePrihoda"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKategorijePrihoda");

                    b.ToTable("KategorijePrihoda");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.KategorijeTroskova", b =>
                {
                    b.Property<int>("IDKategorijaTroska")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKategorijaTroska"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKategorijaTroska");

                    b.ToTable("KategorijeTroskova");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Narudzbe", b =>
                {
                    b.Property<int>("IDNarudzba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNarudzba"));

                    b.Property<double>("CijenaDostave")
                        .HasColumnType("float");

                    b.Property<double>("CijenaPoKomadu")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumIsporuke")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumNabave")
                        .HasColumnType("datetime2");

                    b.Property<int>("DobavljacIDDobavljac")
                        .HasColumnType("int");

                    b.Property<double?>("DodatneNaknade")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Napomene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivArtikla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Porez")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UkupniTrosak")
                        .HasColumnType("float");

                    b.HasKey("IDNarudzba");

                    b.HasIndex("DobavljacIDDobavljac");

                    b.ToTable("Narudzbe");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Natjecaji", b =>
                {
                    b.Property<int>("IDNatjecaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNatjecaj"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dobitnik")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcijenjenaVrijednost")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrajanjeDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TrajanjeOd")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNatjecaj");

                    b.ToTable("Natjecaji");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Poslovnice", b =>
                {
                    b.Property<int>("IDPoslovnica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPoslovnica"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumOtvaranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("RadnoVrijemeDo")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("RadnoVrijemeOd")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPoslovnica");

                    b.ToTable("Poslovnice");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Pozicije", b =>
                {
                    b.Property<int>("IDPozicija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPozicija"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPozicija");

                    b.ToTable("Pozicije");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Pravilnici", b =>
                {
                    b.Property<int>("IDPravilnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPravilnik"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DatumObjavljivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPravilnik");

                    b.ToTable("Pravilnici");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Prihodi", b =>
                {
                    b.Property<int>("IDPrihod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPrihod"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Godina")
                        .HasColumnType("int");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<int>("KategorijePrihodaIDKategorijePrihoda")
                        .HasColumnType("int");

                    b.Property<int?>("Mjesec")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPrihod");

                    b.HasIndex("KategorijePrihodaIDKategorijePrihoda");

                    b.ToTable("Prihodi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Promocije", b =>
                {
                    b.Property<int>("IDPromocije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPromocije"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("DodatniUvjeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoviPromocijaIDTipPromocije")
                        .HasColumnType("int");

                    b.HasKey("IDPromocije");

                    b.HasIndex("TipoviPromocijaIDTipPromocije");

                    b.ToTable("Promocije");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.TipoviPromocija", b =>
                {
                    b.Property<int>("IDTipPromocije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTipPromocije"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTipPromocije");

                    b.ToTable("TipoviPromocija");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Troskovi", b =>
                {
                    b.Property<int>("IDTrosak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTrosak"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Godina")
                        .HasColumnType("int");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<int>("KategorijeTroskovaIDKategorijaTroska")
                        .HasColumnType("int");

                    b.Property<int?>("Mjesec")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTrosak");

                    b.HasIndex("KategorijeTroskovaIDKategorijaTroska");

                    b.ToTable("Troskovi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Velicine", b =>
                {
                    b.Property<int>("IDVelicina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVelicina"));

                    b.Property<string>("Velicina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDVelicina");

                    b.ToTable("Velicine");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Zaposlenici", b =>
                {
                    b.Property<int>("IDZaposlenik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZaposlenik"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Bonus")
                        .HasColumnType("float");

                    b.Property<string>("BrojBankovnogRacuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifikati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavrsetkaRadnogOdnosa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kvalifikacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Placa")
                        .HasColumnType("float");

                    b.Property<int?>("PoslovnicaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prijevoz")
                        .HasColumnType("float");

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TopliObrok")
                        .HasColumnType("float");

                    b.Property<double>("UkupnaPlaca")
                        .HasColumnType("float");

                    b.HasKey("IDZaposlenik");

                    b.HasIndex("PoslovnicaID");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("ArtikliBoje", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Artikli", null)
                        .WithMany()
                        .HasForeignKey("ArtikliIDArtikal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Boje", null)
                        .WithMany()
                        .HasForeignKey("BojeIDBoja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtikliKategorije", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Artikli", null)
                        .WithMany()
                        .HasForeignKey("ArtikliIDArtikal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Kategorije", null)
                        .WithMany()
                        .HasForeignKey("KategorijeIDKategorija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtikliPoslovnice", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Artikli", null)
                        .WithMany()
                        .HasForeignKey("ArtikliIDArtikal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Poslovnice", null)
                        .WithMany()
                        .HasForeignKey("PoslovniceIDPoslovnica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtikliVelicine", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Artikli", null)
                        .WithMany()
                        .HasForeignKey("ArtikliIDArtikal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Velicine", null)
                        .WithMany()
                        .HasForeignKey("VelicineIDVelicina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KandidatiNatjecaji", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Kandidati", null)
                        .WithMany()
                        .HasForeignKey("KandidatiIDKandidat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Natjecaji", null)
                        .WithMany()
                        .HasForeignKey("NatjecajiIDNatjecaj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PozicijeZaposlenici", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Pozicije", null)
                        .WithMany()
                        .HasForeignKey("PozicijeIDPozicija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Zaposlenici", null)
                        .WithMany()
                        .HasForeignKey("ZaposleniciIDZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Artikli", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Brendovi", "Brend")
                        .WithMany("Artikli")
                        .HasForeignKey("BrendIDBrend")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPro.Web.Models.Domains.Dobavljaci", "Dobavljac")
                        .WithMany("Artikli")
                        .HasForeignKey("DobavljacIDDobavljac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brend");

                    b.Navigation("Dobavljac");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Narudzbe", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Dobavljaci", "Dobavljac")
                        .WithMany("Narudzbe")
                        .HasForeignKey("DobavljacIDDobavljac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dobavljac");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Prihodi", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.KategorijePrihoda", "KategorijePrihoda")
                        .WithMany("Prihodi")
                        .HasForeignKey("KategorijePrihodaIDKategorijePrihoda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijePrihoda");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Promocije", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.TipoviPromocija", "TipoviPromocija")
                        .WithMany("Promocije")
                        .HasForeignKey("TipoviPromocijaIDTipPromocije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoviPromocija");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Troskovi", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.KategorijeTroskova", "KategorijeTroskova")
                        .WithMany("Troskovi")
                        .HasForeignKey("KategorijeTroskovaIDKategorijaTroska")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijeTroskova");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Zaposlenici", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Poslovnice", "Poslovnica")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("PoslovnicaID");

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Brendovi", b =>
                {
                    b.Navigation("Artikli");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Dobavljaci", b =>
                {
                    b.Navigation("Artikli");

                    b.Navigation("Narudzbe");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.KategorijePrihoda", b =>
                {
                    b.Navigation("Prihodi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.KategorijeTroskova", b =>
                {
                    b.Navigation("Troskovi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Poslovnice", b =>
                {
                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.TipoviPromocija", b =>
                {
                    b.Navigation("Promocije");
                });
#pragma warning restore 612, 618
        }
    }
}
