// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportPro.Web.Data;

#nullable disable

namespace SportPro.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240423141324_Adding_Zaposlenici_Poslovi_Raspored")]
    partial class Adding_Zaposlenici_Poslovi_Raspored
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportPro.Web.Models.Domains.Natjecaji", b =>
                {
                    b.Property<int>("IDNatjecaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNatjecaj"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dobitnik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcijenjenaVrijednost")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrajanjeDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TrajanjeOd")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNatjecaj");

                    b.ToTable("Natjecaji");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.PonudePoslova", b =>
                {
                    b.Property<int>("IDPonudaPoslova")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPonudaPoslova"));

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("int");

                    b.Property<double>("BrojSati")
                        .HasColumnType("float");

                    b.Property<double>("CijenaSata")
                        .HasColumnType("float");

                    b.Property<DateTime>("KrajRadova")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisPosla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetakRadova")
                        .HasColumnType("datetime2");

                    b.Property<string>("PotrebnaOprema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPonudaPoslova");

                    b.ToTable("PonudePoslova");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Poslovi", b =>
                {
                    b.Property<int>("IDPosla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPosla"));

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("int");

                    b.Property<double>("BrojSati")
                        .HasColumnType("float");

                    b.Property<double>("CijenaSata")
                        .HasColumnType("float");

                    b.Property<DateTime>("KrajRadova")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisPosla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetakRadova")
                        .HasColumnType("datetime2");

                    b.Property<string>("PotrebnaOprema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Profit")
                        .HasColumnType("float");

                    b.Property<int?>("RasporedIDRaspored")
                        .HasColumnType("int");

                    b.Property<double>("Trosak")
                        .HasColumnType("float");

                    b.HasKey("IDPosla");

                    b.HasIndex("RasporedIDRaspored");

                    b.ToTable("Poslovi");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Raspored", b =>
                {
                    b.Property<int>("IDRaspored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRaspored"));

                    b.Property<double>("BrojSati")
                        .HasColumnType("float");

                    b.Property<DateTime>("KrajRada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetakRada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Posao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zaposlenik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDRaspored");

                    b.ToTable("Raspored");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Zaposlenici", b =>
                {
                    b.Property<int>("IDZaposlenik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZaposlenik"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cerfitikati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Placa")
                        .HasColumnType("float");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RasporedIDRaspored")
                        .HasColumnType("int");

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDZaposlenik");

                    b.HasIndex("RasporedIDRaspored");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Poslovi", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Raspored", null)
                        .WithMany("Poslovi")
                        .HasForeignKey("RasporedIDRaspored");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Zaposlenici", b =>
                {
                    b.HasOne("SportPro.Web.Models.Domains.Raspored", null)
                        .WithMany("Zaposlenici")
                        .HasForeignKey("RasporedIDRaspored");
                });

            modelBuilder.Entity("SportPro.Web.Models.Domains.Raspored", b =>
                {
                    b.Navigation("Poslovi");

                    b.Navigation("Zaposlenici");
                });
#pragma warning restore 612, 618
        }
    }
}
